server:
  port: 8082
  servlet:
    context-path: /api/v1.0
  tomcat:
    threads:
      max: 200
      min-spare: 10
  websocket:
    handshake:
      timeout: 5000

spring:
  application:
    name: mpcs-backend
  config:
    import: optional:file:.env[.properties],optional:file:../.env[.properties]
  profiles:
    active: ci
  thymeleaf:
    mode: HTML
    cache: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"
  level:
    root: INFO
    com.ricky.collaboration: DEBUG
    org:
      ansj: DEBUG
      com.alibaba.cloud.ai.dashscope: DEBUG
