package com.ricky.common.exception;

import lombok.Getter;


/**
 * @author Ricky
 * @version 1.0
 * @date 2024/9/9
 * @className ErrorCodeEnum
 * @desc 错误码
 * 400：请求验证错误，请求中资源所属关系错误等
 * 401：认证错误
 * 403：权限不够
 * 404：资源未找到
 * 409：业务异常
 * 426：套餐检查失败
 * 500：系统错误
 */
@Getter
public enum ErrorCodeEnum {

    // 400
    PARAMS_ERROR(400),
    INVALID_EPS(400),
    INVALID_ENUM_KEY(400),
    REQUEST_VALIDATION_FAILED(400),
    UNSUPPORTED_FILE_TYPES(400),
    FILE_MUST_NOT_BE_EMPTY(400),
    FILE_ORIGINAL_NAME_MUST_NOT_BE_BLANK(400),
    HAS_SENSITIVE_WORD(400),
    INVALID_ID_PREFIX(400),

    // 401
    AUTHENTICATION_FAILED(401),

    // 403
    ACCESS_DENIED(403),

    // 404
    NOT_FOUND(404),
    AR_NOT_FOUND(404),
    AR_NOT_FOUND_ALL(404),
    DOMAIN_EVENT_NOT_FOUND(404),
    FILE_NOT_FOUND(404),
    FOLDER_NOT_FOUND(404),
    FOLDER_HIERARCHY_NOT_FOUND(404),

    // 409
    FILE_ALREADY_EXISTS(409),
    FILE_READ_FAILED(409),
    FILE_DELETE_FAILED(409),
    INVALID_HASH_ALGORITHM(409),
    UNSUPPORTED_FILE_TYPE(409),
    STORE_FILE_FAILED(409),
    EXTRACT_METADATA_FAILED(409),
    MUST_SIGN_AGREEMENT(409),
    VERIFICATION_CODE_COUNT_OVERFLOW(409),
    VERIFICATION_CODE_CHECK_FAILED(409),
    USER_WITH_MOBILE_OR_EMAIL_ALREADY_EXISTS(409),
    VERIFICATION_CODE_ALREADY_SENT(409),
    TOO_MANY_VERIFICATION_CODE_FOR_TODAY(409),
    USER_ALREADY_LOCKED(409),
    UPLOAD_NOT_COMPLETE(409),
    UPLOAD_ALREADY_COMPLETED(409),
    SAVE_CHUNK_FAILED(409),
    MERGE_CHUNKS_FAILED(409),
    FILE_HASH_MISMATCH(409),
    FILE_NAME_DUPLICATES(409),
    FOLDER_HIERARCHY_TOO_DEEP(409),
    FOLDER_WITH_NAME_ALREADY_EXISTS(409),
    FOLDER_NAME_DUPLICATES(409),

    // 426

    // 429
    TOO_MANY_REQUEST(429),

    // 500
    SYSTEM_ERROR(500),
    ;

    /**
     * 错误码
     */
    private final int status;

    ErrorCodeEnum(int status) {
        this.status = status;
    }

}
